# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/mmmmt
Accept: application/json

###

GET 127.0.0.1:8000/add/1/2
Accept: application/json